title:            zhuf
description:      zhuf's notes
url:              http://zhuf.github.io
signoff:          zhufeng
disqus_shortname: zhuf
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-40977469-1

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://zhuf.github.io
  - name:         Email
    url:          mailto:zhufeng9282@163.com
    external:     true
  - name:         GitHub
    url:          http://github.com/zhuf
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
